export const FETCH_COIN_DATA = "FETCH_COIN_DATA";
export const FETCH_COIN_DATA_PENDING = "FETCH_COIN_DATA_PENDING";
export const FETCH_COIN_DATA_FULFILLED = "FETCH_COIN_DATA_FULFILLED";
export const FETCH_COIN_DATA_REJECTED = "FETCH_COIN_DATA_REJECTED";
